[package]
authors = ["David Irvine <david.irvine@maidsafe.net>"]
name = "i2c-pca9685"
version = "0.1.9-pre"
license = "MIT/Apache-2.0"
readme = "README.md"
description = "PCA9685 driver for i2cbus"
repository = "https://github.com/dirvine/i2c-pca9685"

[dependencies]
i2cdev = "~0.3.1"
